/* eslint-disable prettier/prettier */
export enum ActionType {
    //AuthAction
    REGISTER            = 'register',
    // REGISTER_SUCCESS = 'register_success',
    REGISTER_FAILED     = 'register_failed',
    PASSWORD_MISMATCH   = 'password_mismatch',
    PASSWORD_MISMATCH_FAILED = 'password_mismatch_failed',
    LOGIN               = 'login',
    LOGIN_SUCCESS       = 'login_success',
    LOGIN_FAILED        = 'login_failed',
    LOGOUT              = 'logout',
    LOGOUT_SUCCESS      = 'logout_success',
    //ListAction
    INIT_ONLINE_LIST        = 'init_online_list',
    ONLINE_LIST             = 'online_list',
    INIT_SEARCH             = 'init_search',
    SEARCH_NOT_FOUND        = 'search_not_found',
    SEARCH_LIST             = 'search_list',
    INIT_CONTACT_LIST       = 'init_contact_list',
    CONTACT_LIST            = 'contact_list',
    CONTACT_LIST_REVERSE    = 'contact_list_reverse',
    INIT_RECENT_CHAT_LIST   = 'init_recent_chat_list',
    RECENT_CHAT_LIST_REVERSE= 'recent_chat_list_reverse',
    RECENT_CHAT_LIST        = 'recent_chat_list',
    INVITE_USER             = 'invite_user',
    //ProfileAction
    STORE_PROFILE           = 'store_profile',
    GET_PROFILE             = 'get_profile',
    STORE_PROFILE_RESULT    = 'store_profile_result',
    //MsgAction
    LOADING_MSG		        = 'loading_msg',
    NO_USER_ALERT		    = 'no_user_alert',
    FETCH_MSG			    = 'fetch_msg',
    FETCH_MSG_RESULT	    = 'fetch_msg_result',
    SENDING_MSG			    = 'sending_msg',
    SEND_MSG			    = 'send_msg',
    SEND_MSG_RESULT			= 'send_msg_result',
    CLEAR_MSG			    = 'clear_msg',
    STORE_IMAGE             = 'store_image',
    STORE_IMAGE_RESULT      = 'store_image_result',
    RESET_MSG			    = 'reset_msg',
    ERROR_MSG			    = 'error_msg',
}
